[package]
name = "rust"
version = "0.1.0"
edition = "2018"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = [ "cdylib" ]
path = "src/main/rust/lib.rs"

[dependencies]
jni = { version = "0.19.0" }
